# Generated by Django 4.2.16 on 2024-10-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('name_for_str_metafield', models.CharField(blank=True, max_length=128, null=True)),
                ('str_value', models.CharField(blank=True, max_length=128, null=True)),
                ('name_for_numeric_metafield', models.CharField(blank=True, max_length=128, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('name_for_date_metafield', models.CharField(blank=True, max_length=128, null=True)),
                ('begin', models.DateField(blank=True, max_length=128, null=True)),
                ('end', models.DateField(blank=True, max_length=128, null=True)),
                ('LOBID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lineofbusiness')),
            ],
        ),
    ]
