# Generated by Django 4.2.16 on 2024-10-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='products_images')),
                ('LOBID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lineofbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMetaFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.metafield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='DateMetaField',
            fields=[
                ('product_metafield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.productmetafields')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NumberMetaField',
            fields=[
                ('product_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.productmetafields')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StringMetaField',
            fields=[
                ('product_metafield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.productmetafields')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
    ]
